baseURL = "https://mcrunix.io/"
languageCode = "en-us"
title = "Masoud Ghorbani"
theme = "whitepaper"
summaryLength = 20
pygmentsUseClasses = true
pygmentsCodeFences = true
disqusShortname = "mcrunix"
googleAnalytics = "UA-109595753-1"

[permalinks]
  posts = "/:year/:month/:title/"

[params]
  author = "Masoud Ghorbani"
  description = "I write software. Occasionally, I will build things to learn and use."
  customDateFormat = "January 2, 2006"
